In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import joblib

In [3]:
df = pd.read_csv(
    r"D:\Ai_project\AI_Sales_Prediction_Dashboard\processed_data\cleaned_data.csv"
)

In [4]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,profit,shipping_cost,order_priority,year,month,month_name,day,day_of_week,quarter,revenue
0,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,106.140,35.46,Medium,2011,1,January,1,Saturday,1,408
1,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,36.036,9.72,Medium,2011,1,January,1,Saturday,1,120
2,HU-2011-1220,2011-01-01,2011-05-01,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,29.640,8.17,High,2011,1,January,1,Saturday,1,66
3,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,-26.055,4.82,High,2011,1,January,1,Saturday,1,45
4,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,37.770,4.70,Medium,2011,1,January,1,Saturday,1,114

In [5]:
df.shape

(51290, 27)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  int64
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
 21  month           51290 non-null  int64
 22  month_name      51290 non-null  str
 23  day             51290 non-null  int64
 24  day_of_week     51290 non-null  str
 25  quarter         51290 non-null  int64
 26  revenue         51290 non-null  int64
dtypes: float64(3), int64(7), str(17)
memory usage: 19.5 MB

In [7]:
print(df["year"].dtype)

int64

In [8]:
print(df["month"].dtype)

int64

In [9]:
features = [
    "year",
    "month",
    "quantity",
    "discount",
    "profit",
    "category",
    "region",
    "segment"
]

X = df[features]

y = df["sales"]

In [10]:
X = pd.get_dummies(
    X,
    drop_first=True
)

In [11]:
X.head()

,year,month,quantity,discount,profit,category_Office Supplies,category_Technology,region_Canada,region_Caribbean,region_Central,...,region_EMEA,region_East,region_North,region_North Asia,region_Oceania,region_South,region_Southeast Asia,region_West,segment_Corporate,segment_Home Office
0,2011,1,2,0.0,106.140,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2011,1,3,0.1,36.036,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,2011,1,4,0.0,29.640,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,2011,1,3,0.5,-26.055,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
4,2011,1,5,0.1,37.770,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [12]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.20,
    random_state=42
)

In [14]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(41032, 21)
(10258, 21)
(41032,)
(10258,)

In [15]:
linear_model = LinearRegression()

linear_model.fit(
    X_train,
    y_train
)

LinearRegression()

In [16]:
linear_predictions = linear_model.predict(
    X_test
)

In [17]:
mae = mean_absolute_error(
    y_test,
    linear_predictions
)

print("MAE:", mae)

MAE: 186.83120932755318

In [18]:
mse = mean_squared_error(
    y_test,
    linear_predictions
)

print("MSE:", mse)

MSE: 131030.68427682319

In [19]:
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 361.98160764992355

In [20]:
r2 = r2_score(
    y_test,
    linear_predictions
)

print("R² Score:", r2)

R² Score: 0.4643943174406465

In [21]:
comparison = pd.DataFrame({

    "Actual Sales": y_test.values,

    "Predicted Sales": linear_predictions

})

comparison.head(10)

   Actual Sales  Predicted Sales
0            86       244.923338
1            18        36.552971
2            20         2.047742
3            60       289.416301
4          1791      1281.786121
5           171       367.055252
6            10       314.036243
7          1220       597.831413
8             7       -37.230559
9            57       147.393940

In [22]:
rf_model = RandomForestRegressor(

    n_estimators=100,

    random_state=42

)

rf_model.fit(

    X_train,

    y_train

)

RandomForestRegressor(random_state=42)

In [23]:
rf_predictions = rf_model.predict(

    X_test

)

In [24]:
print(

    "MAE:",

    mean_absolute_error(

        y_test,

        rf_predictions

    )

)

print(

    "RMSE:",

    np.sqrt(

        mean_squared_error(

            y_test,

            rf_predictions

        )

    )

)

print(

    "R²:",

    r2_score(

        y_test,

        rf_predictions

    )

)

MAE: 103.92696317392232
RMSE: 249.67588683672506
R²: 0.7451847772661822

In [25]:
joblib.dump(

    rf_model,

    r"D:\Ai_project\AI_Sales_Prediction_Dashboard\models\sales_prediction_model.pkl"

)

['D:\\Ai_project\\AI_Sales_Prediction_Dashboard\\models\\sales_prediction_model.pkl']

In [26]:
joblib.dump(

    scaler,

    r"D:\Ai_project\AI_Sales_Prediction_Dashboard\models\scaler.pkl"

)

['D:\\Ai_project\\AI_Sales_Prediction_Dashboard\\models\\scaler.pkl']

In [27]:
loaded_model = joblib.load(

    r"D:\Ai_project\AI_Sales_Prediction_Dashboard\models\sales_prediction_model.pkl"

)

In [28]:
prediction = loaded_model.predict(

    X_test[:5]

)

print(prediction)

[  40.06   27.87   44.3    82.91 2066.24]